apiVersion: v1
kind: ServiceAccount
metadata:
  name: fitness-app-sa
  namespace: default
  annotations:
    # This Client ID tells Workload Identity which Azure Identity to assume
    # Replace the value below with the Client ID(managed identity)
    azure.workload.identity/client-id: "e587635c-c1d4-482f-89bc-35e1010d01e6"
  labels:
    azure.workload.identity/use: "true"
